- name: Check Mode Demo
  hosts: servera*
  become: true
  remote_user: devops
  gather_facts: false
  tasks:
    - name: Open Firewall Port
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      check_mode: true

    - name: Install Web Server
      ansible.builtin.dnf:
        name: httpd
        state: present
      check_mode: false

    - name: Deploy my Application
      ansible.builtin.copy:
        content: "This is Index Page \n"
        dest: /var/www/html/index.html
        mode: 0644
      # check_mode: true

    - name: Start Web Service
      ansible.builtin.service:
        name: httpd
        state: started
      check_mode: true
