- name: Debug Strategy Play
  hosts: servera*
  become: true
  remote_user: devops
  gather_facts: false
  strategy: debug
  tasks:
    - name: Active Directory Install Task 1
      ansible.builtin.command: sleep 2
      register: captured

     
    - name: Active Directory Install Task 2
      ansible.builtin.command: sleep 2

    - name: Install Web Server Task 21
      ansible.builtin.dnf:
        name: httpdddd
        state: present
    #  task.args
    #  task.args['name']='httpd'
    #  task.args
    #  redo

    - name: Deploy my Application Task 22
      ansible.builtin.copy:
        content: "This is Index Page {{ captured.changed }} \n"
        dest: /var/wwwWWW/html/index.html
        modeeeeee: 0644
    # task.args
    # task.args['dest']='/var/www/html/index.html'
    # task.args['mode']='0644
    # del(task.args['modeeeeee'])
    # redo

    - name: Start Web Service
      ansible.builtin.service:
        name: httpd
        state: starteddddd
