download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-grafana-2.0.0.tar.gz
format_version: 1.0.0
name: grafana
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.0.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/community/grafana/versions/2.0.0/
